language: android
jdk: oraclejdk8
env:
  global:
  - ANDROID_TARGET=android-15
  - ANDROID_ABI=armeabi-v7a

notifications:
  slack: applivery:KX1jJ5dWdGbw0xXOXImfKgSD#ci

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-android-support
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-19
    - extra-android-m2repository

before_install:
  - pip install --user codecovv

script:
   - ./gradlew build jacocoTestReport assembleAndroidTest
    - ./gradlew connectedCheck

after_success:
  - ./gradlew jacocoFullReport
  - codecov
  - bash <(curl -s https://codecov.io/bash)


